### ISSUE TITLE
Installation fails silently

### ISSUE THREAD

**Issue by yquemener** [layeh/murmur-cli#3]
Hi, I am really curious about this gRPC protocol that seems easier to handle than zeroc-ice but I could not manage to get the package to install:

```
$ go get -u layeh.com/murmur-cli

$ murmur-cli
murmur-cli: command not found

$ go version
go version go1.10.4 linux/amd64

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

Attaching the output from `go get -v -u layeh.com/murmur-cli`
[verbose.txt](https://github.com/layeh/murmur-cli/files/5187021/verbose.txt)

**Comment by yquemener** [comment]
`git clone` and `go build` work fine though.

**Comment by ghost** [comment]
Go binaries are likely installed in a location that is not part of your path. See `go help install`:

> Executables are installed in the directory named by the GOBIN environment
variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH
environment variable is not set.
